services:
  api-metaflow-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}

  evolution_api:
    image: atendai/evolution-api:v1.8.7
    container_name: evolution_api
    ports:
      - 8080:8080
    environment:
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
    depends_on:
      - api-metaflow-pg
